const EXIT_CODES = {
    SUCCESS: 0,
    CONFIG_NOT_FOUND: 1,
    CONFIG_UNPARSABLE: 2,
    CONFIG_URL_INFER_FAILED: 3,
    THEME_NOT_FOUND: 11,
    THEME_SCRIPT_ERROR: 12,
    THEME_UNPARSABLE: 13,
    THEME_I18N_ERROR: 14,
    SOURCE_PATH_INACCESSIBLE: 21,
    BUILD_PATH_INACCESSIBLE: 22,
    LOCAL_FS_ERROR: 23,
    RENDER_ERROR: 31,
    DEPLOYER_ERROR: 32,
};

export default EXIT_CODES;